FROM node

# Make new directory
RUN mkdir cucumberProtractorTest

# Make new directory for app after copy
RUN mkdir cucumberProtractorWorkDir

# Change directory to newly created directory
WORKDIR /cucumberProtractorWorkDir

